export const TYPES = {
  User: Symbol.for('User'),
  Category: Symbol.for('Category'),
  Product: Symbol.for('Product'),
  ProductVariant: Symbol.for('ProductVariant'),
  Review: Symbol.for('Review'),
  Seller: Symbol.for('Seller'),
  Admin: Symbol.for('Admin'),
  Address: Symbol.for('Address'),
  Cart: Symbol.for('Cart'),
  PaymentOption: Symbol.for('PaymentOption'),
  Payment: Symbol.for('Payment'),
  Bid: Symbol.for('Bid'),
  BidMessages: Symbol.for('BidMessages'),
  Order: Symbol.for('Order'),
  UserView: Symbol.for('UserView'),
  ShippingZone: Symbol.for('ShippingZone'),
  Attribute: Symbol.for('Attribute'),
  AttributeValue: Symbol.for('AttributeValue'),
  Notification: Symbol.for('Notification'),

  AuthService: Symbol.for('AuthService'),
  AdminService: Symbol.for('AdminService'),
  CategoryService: Symbol.for('CategoryService'),
  ProductService: Symbol.for('ProductService'),
  ReviewService: Symbol.for('ReviewServices'),
  UserService: Symbol.for('UserService'),
  AddressService: Symbol.for('AddressService'),
  CartService: Symbol.for('CartService'),
  PaymentOptionService: Symbol.for('PaymentOptionService'),
  PaymentService: Symbol.for('PaymentService'),
  ProductBidService: Symbol.for('ProductBidService'),
  BidMessageService: Symbol.for('BidMessageService'),
  OrderService: Symbol.for('OrderService'),
  ViewTrackingService: Symbol.for('ViewTrackingService'),
  ShippingZoneService: Symbol.for('ShippingZoneService'),
  AttributeService: Symbol.for('AttributeService'),
  AttributeValueService: Symbol.for('AttributeValueService'),
  SellerService: Symbol.for('SellerService'),
  NotificationService: Symbol.for('NotificationService'),

  RequireSignIn: Symbol.for('RequireSignIn'),
  RequireSeller: Symbol.for('RequireSeller'),
  RequireAdmin: Symbol.for('RequireAdmin'),
  OptionalAuth: Symbol.for('OptionalAuth'),
};
export default TYPES;
