export const TYPES = {
  User: Symbol.for('User'),
  Category: Symbol.for('Category'),
  Product: Symbol.for('Product'),
  ProductVariant: Symbol.for('ProductVariant'),
  Review: Symbol.for('Review'),
  Seller: Symbol.for('Seller'),
  Address: Symbol.for('Address'),
  Cart: Symbol.for('Cart'),
  PaymentOption: Symbol.for('PaymentOption'),
  Bid: Symbol.for('Bid'),
  BidMessages: Symbol.for('BidMessages'),
  Order: Symbol.for('Order'),

  AuthService: Symbol.for('AuthService'),
  CategoryService: Symbol.for('CategoryService'),
  ProductService: Symbol.for('ProductService'),
  ReviewService: Symbol.for('ReviewServices'),
  UserService: Symbol.for('UserService'),
  AddressService: Symbol.for('AddressService'),
  CartService: Symbol.for('CartService'),
  PaymentOptionService: Symbol.for('PaymentOptionService'),
  ProductBidService: Symbol.for('ProductBidService'),
  BidMessageService: Symbol.for('BidMessageService'),
  OrderService: Symbol.for('OrderService'),

  RequireSignIn: Symbol.for('RequireSignIn'),
  RequireSeller: Symbol.for('RequireSeller'),
  OptionalAuth: Symbol.for('OptionalAuth'),
};
export default TYPES;
