const constants = {
  mongooseModels: {
    USER: 'User',
    SELLER: 'Seller',
    ADMIN: 'Admin',
    PRODUCT: 'Product',
    PRODUCT_VARIANT: 'ProductVariant',
    CATEGORY: 'Category',
    BRAND: 'Brand',
    REVIEW: 'Review',
    ADDRESS: 'Address',
    CART: 'Cart',
    PAYMENT_OPTION: 'PaymentOption',
    BID: 'Bid',
    BIDMESSAGES: 'BidMessages',
    ORDER: 'Order',
    PAYMENT: 'Payment',
    USER_VIEW: 'UserView',
    SHIPPING_ZONE: 'ShippingZone',
    ATTRIBUTE: 'Attribute',
    ATTRIBUTE_VALUE: 'AttributeValue',
    TOKEN_BLACKLIST: 'TokenBlacklist',
    PAYOUT: 'Payout',
    AUDIT_LOG: 'AuditLog',
    BID_OFFER: 'BidOffer',
  },
};
export default constants;
