const constants = {
  mongooseModels: {
    USER: 'User',
    SELLER: 'Seller',
    ADMIN: 'Admin',
    PRODUCT: 'Product',
    PRODUCT_VARIANT: 'ProductVariant',
    CATEGORY: 'Category',
    BRAND: 'Brand',
    REVIEW: 'Review',
    ADDRESS: 'Address',
    CART: 'Cart',
    PAYMENT_OPTION: 'PaymentOption',
    BID: 'Bid',
    BIDMESSAGES: 'BidMessages',
    CONVERSATION: 'Conversation',
    CONVERSATION_PRODUCT: 'ConversationProduct',
    MESSAGE: 'Message',
    OFFER: 'Offer',
    ORDER: 'Order',
    PAYMENT: 'Payment',
    USER_VIEW: 'UserView',
    SHIPPING_ZONE: 'ShippingZone',
    ATTRIBUTE: 'Attribute',
    ATTRIBUTE_VALUE: 'AttributeValue',
    MARKETING_CAMPAIGN: 'MarketingCampaign',
    ADMIN_EMAIL_BROADCAST: 'AdminEmailBroadcast',
  },
};

export default constants;
